##########################################################################
# Configuration example: copy this example and rename it to "config.yml"
# to configure the application
##########################################################################

# Configuration of the SSH client
ssh:
    # If true, then ssh connection will be established using the key pair defined by publicKeyFilePath and privateKeyFilePath
    # Otherwise, a new ssh keypair will be generated in a application-specific temp folder
    useExistingKeyPair:
    # Path to the public key that will be sent on the EC2 instance
    publicKeyFilePath:
    # Path to the private key that will be used to authenticate
    privateKeyFilePath:
# List of instances to connect to
instances:
    # User-friendly EC2 instance name that will appear in the instance list
    # This does **not** have to be the same name as the EC2 instance in AWS
    - name:
      # EC2 instance ID
      id:
      # EC2 instance region (e.g us-east-1, eu-west-2)
      region:
      # EC2 instance availibity zone (e.g eu-west-2a)
      availibilityZone:
      # username to use when establishing the SSH connection (usually 'ubuntu' or 'ssm-user')
      shellUser:
      # Optional, a list of port forwarding configs. Used to forward traffic from this computer to a remote host via the EC2 instance
      portForwardingOptions:
          # Name of this configuration (will be used to display the list of choices)
          - name:
            # Local machine port
            localPort:
            # Remote host address
            remoteHost:
            # Remote host port
            remotePort:
